version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env-prod

  db:
    container_name: db
    image: postgres:16.2

    restart: always
    ports:
      - 5432:5432
